package proyecto2;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author Jenderson Quintero y Norangel Marin.
 */
public class Interfaz extends javax.swing.JFrame {
    
    Arbol arbol = new Arbol();
    Grafico grafico = new Grafico();
    Funcionalidades f = new Funcionalidades(arbol, grafico);
    JFrame ventana = new JFrame("Representación grafica del Árbol");
    JScrollPane ampliar = new JScrollPane(grafico);
    
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        arbol.AdivinadorPrev();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        año = new javax.swing.JLabel();
        autores = new javax.swing.JLabel();
        Mostrar = new javax.swing.JButton();
        marco = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(204, 255, 153));
        fondo.setMinimumSize(new java.awt.Dimension(528, 150));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Adivinador de Animales");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 40));

        salir.setBackground(new java.awt.Color(204, 0, 0));
        salir.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setText("x");
        salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        salir.setBorderPainted(false);
        salir.setFocusPainted(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fondo.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 40, 30));

        iniciar.setForeground(new java.awt.Color(0, 0, 0));
        iniciar.setText("Iniciar Sesión");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        fondo.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 360, -1));

        limpiar.setForeground(new java.awt.Color(0, 0, 0));
        limpiar.setText("Limpiar Base de Conocimientos");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        fondo.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 360, -1));

        año.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        año.setForeground(new java.awt.Color(0, 0, 0));
        año.setText("2020");
        fondo.add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        autores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        autores.setForeground(new java.awt.Color(0, 0, 0));
        autores.setText("© Norangel Marín y Jenderson Quintero");
        fondo.add(autores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        Mostrar.setForeground(new java.awt.Color(0, 0, 0));
        Mostrar.setText("Mostrar Base de Conocimientos ");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        fondo.add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 360, -1));

        marco.setBackground(new java.awt.Color(153, 255, 51));
        fondo.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 400, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        arbol.Adivinador();
        f.actualizarArbol();
    }//GEN-LAST:event_iniciarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        arbol.vaciarArbol();
        arbol.txt.vaciarTxt();
        f.actualizarArbol();
    }//GEN-LAST:event_limpiarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        f.actualizarArbol();
        ampliar.setBounds(0, 0, 900, 700);
        ventana.setExtendedState(6);
        ventana.setMinimumSize(new Dimension(900, 700));
        ventana.setLocationRelativeTo(null);
        ventana.setDefaultCloseOperation(1);
        ventana.getContentPane().add(ampliar);
        ventana.setVisible(true);
    }//GEN-LAST:event_MostrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JLabel autores;
    private javax.swing.JLabel año;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton limpiar;
    private javax.swing.JPanel marco;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
